//http://localhost:8000/
###

POST http://localhost:8000/curso
Content-Type: application/json

{
    "nome":"ADS",
    "duracao": 5,
    "descricao":"curso do integrado",
    "valor": 740.09,
    "tipoId": 2,
    "modalidadeId": 2,
    "imagemCurso": "https://firebasestorage.googleapis.com/v0/b/endless-sol-403405.appspot.com/o/images%2FR.png?alt=media&token=ee2f4c9d-7dc5-4891-a8e1-039287bf9c2a"
}

###
GET http://localhost:8000/curso



### 
PATCH http://localhost:8000/curso/1
Content-Type: application/json

{
    "duracao": 2.5
}

###
DELETE http://localhost:8000/curso/1



# { exemplo de json para criar um futuro_aluno
#   "nome": "joao pedro",
#   "CPF": "12335678910",
#   "telefone": "44998176275",
#   "email": "joaopedro@gmail.com",
#   "CEP": "87250-000", 
#   "dataNascimento": "2022-09-27",
#   "imagemDoocumento": "teste",
#   "cursoId": 1
# }

# { exemplo de json para criar uma modalidade
#   "nome": "Presencial"
# }

# { Exemplo de JSON para criar um tipo
#     "nome": "Pos-Graduacao",
#   "nomeDeExibicao": "Pós-Graduação"
# }
