//http://localhost:3000/

GET http://localhost:3000/curso/

###

GET http://localhost:3000/curso/id/1

###

POST http://localhost:3000/curso
Content-Type: application/json

{
    "nome":"direito",
    "duracao": 5,
    "tipo":false,
    "descricao":"curso do integrado",
    "modalidade": "presencial",
    "valor": 740.09
}

###
GET http://localhost:3000/curso/nome/ads


### 
PATCH http://localhost:3000/curso/1
Content-Type: application/json

{
    "descricao":"curso presencial do integrado"
}

###
DELETE http://localhost:3000/curso/2